language: php

php:
# - 5.3 # requires old distro, see below
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise

install:
  - composer install

script:
  - vendor/bin/phpunit
  - php compile.php
  - ./tests/acceptance.sh
